### ISSUE TITLE
Login, Logout Page

### ISSUE THREAD

**Issue by ElginL** [ElginL/orbital-splinkty#2]
To Dos:

- [x] - Create frontend user interface for log in page
- [x] - Create Stack Navigation to navigate from log in to sign up page
- [x] - Create frontend user sign up page
- [x] - Linking frontend and backend

**Comment by weesiau** [comment]
- [x] Add checks for email and password entry 
- [x] Add functionality for confirm password (re-entry)

**Comment by ElginL** [comment]
Log in and Log out functionalities done, still have a little more to touch up on.
- [x] Styling log in page
- [x] Styling log out page
- [x] Code clean up

**Comment by weesiau** [comment]
- [ ] Add Google authentication option
- [ ] Add Apple authentication option

**Comment by ElginL** [comment]
completed
