### ISSUE TITLE
Google vision API

### ISSUE THREAD

**Issue by ElginL** [ElginL/orbital-splinkty#21]
- [x] - Have something that can detect text
- [x] - Ability to get useful texts
- [x] - Can upload image to scan
- [x] - Can take a photo to scan
- [x] - A page listing all of the items scanned

**Comment by weesiau** [comment]
Implemented basic ability to detect and extract useful text from a receipt

**Comment by weesiau** [comment]
Processing of receipt photo is moved to server side - improvements on accuracy required
